export const MOCKUP_POSTS = [
  {
    id: "lead-post",
    title: "When Courts Look Past the Contract: The Doctrine of Substance Over Form",
    slug: "courts-look-past-contract-substance-over-form",
    category: "Corporate Law",
    featured: true,
    trending: false,
    author: "Siddh Dhingra",
    excerpt: "\"A contract can say whatever it wants. Courts don't always care.\" — The principle that voids clever structuring and exposes trustees to criminal liability.",
    coverImage: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=2070&auto=format&fit=crop",
    createdAt: "2026-04-18T10:00:00Z",
    updatedAt: "2026-04-18T10:00:00Z",
    readingTime: 8,
    status: "PUBLISHED",
    tags: "Corporate Law, Fiduciary Duty",
    layoutType: "editorial",
    content: JSON.stringify({
      type: 'doc',
      content: [
        { type: 'paragraph', content: [{ type: 'text', text: 'A public trust. Private property. Everyone knows that property cannot be transferred. So someone got creative — brought in a private entity, gave them full rights to operate and manage the entire asset, collect all profits, and pay the trust a token fee. They called it a "Management Agreement".' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'It felt clever. It looked clean on paper. Until courts applied one principle that cuts through all of it: Substance Over Form. The doctrine holds that what you call an agreement is irrelevant. What matters is what it actually does.' }] },
        { type: 'paragraph', content: [{ type: 'text', text: 'Courts have repeatedly disregarded such agreements — and the consequences enter beyond civil liability. Trustees face criminal exposure under breach of fiduciary duty provisions. The message is clear: clever drafting is not a shield.' }] }
      ]
    }),
  },
  {
    id: "side-1",
    title: "The 110-Crore Contract That was 2 Pages Long",
    slug: "110-crore-contract-2-pages",
    category: "Contract Law",
    featured: false,
    trending: true,
    author: "The Solitic Core",
    excerpt: "Of guaranteed agreements vs real-world performance. See what happens when they fail.",
    coverImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2070&auto=format&fit=crop",
    createdAt: "2026-04-12T10:00:00Z",
    updatedAt: "2026-04-12T10:00:00Z",
    readingTime: 5,
    status: "PUBLISHED",
    tags: "Contract Law, Strategy",
    layoutType: "magazine",
    content: JSON.stringify({
      type: 'doc',
      content: [{ type: 'paragraph', content: [{ type: 'text', text: 'In a world of 50-page Master Service Agreements, one firm decided to simplify. It cost them 110 crores.' }] }]
    }),
  },
  {
    id: "side-2",
    title: "Suicide by Valuation: How Early Fundraising kills Profitability",
    slug: "suicide-by-valuation",
    category: "Startup Law",
    featured: false,
    trending: true,
    author: "Siddh Dhingra",
    excerpt: "A founder raised at a valuation that had no business existing. Now investors won't let him raise more.",
    coverImage: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?q=80&w=2070&auto=format&fit=crop",
    createdAt: "2026-04-11T10:00:00Z",
    updatedAt: "2026-04-11T10:00:00Z",
    readingTime: 6,
    status: "PUBLISHED",
    tags: "Venture Capital, Valuation",
    layoutType: "report",
    content: JSON.stringify({
      type: 'doc',
      content: [{ type: 'paragraph', content: [{ type: 'text', text: 'The vanity of the unicorn tag often hides the rot of terminal liquidation preferences.' }] }]
    }),
  },
  {
    id: "side-3",
    title: "Paying Less Costs More: The Hidden Economics of Employee Retention",
    slug: "paying-less-costs-more",
    category: "Governance",
    featured: false,
    trending: true,
    author: "CA Ashish Tiwari",
    excerpt: "Small businesses lose talent trying to save money on salaries.",
    coverImage: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=1974&auto=format&fit=crop",
    createdAt: "2026-04-10T10:00:00Z",
    updatedAt: "2026-04-10T10:00:00Z",
    readingTime: 4,
    status: "PUBLISHED",
    tags: "Human Resources, Economics",
    layoutType: "minimal",
    content: JSON.stringify({
      type: 'doc',
      content: [{ type: 'paragraph', content: [{ type: 'text', text: 'The true cost of churn far exceeds the incremental cost of a competitive salary.' }] }]
    }),
  },
  {
    id: "grid-1",
    title: "M&A has tightened ROC filling procedures",
    slug: "ma-tightened-roc-filing",
    category: "Regulatory Desk",
    featured: false,
    trending: false,
    author: "The Solitic Core",
    excerpt: "Amended rules now apply from Buy 1st delay. Businesses with pending more lead filings should act immediately.",
    createdAt: "2026-04-09T10:00:00Z",
    updatedAt: "2026-04-09T10:00:00Z",
    readingTime: 3,
    status: "PUBLISHED",
    tags: "Compliance, Regulatory",
    layoutType: "spotlight",
    content: JSON.stringify({ type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'The Registrar of Companies is no longer a passive observer.' }] }] }),
  },
  {
    id: "grid-2",
    title: "Raising Too Early at Too High a Valuation is Financial Suicide",
    slug: "raising-too-early-financial-suicide",
    category: "Startup Law",
    featured: false,
    trending: true,
    author: "Siddh Dhingra",
    excerpt: "A look into optics vs safety. No revenue, yet an inflated valuation at a rate that made future investors walk before sitting down.",
    createdAt: "2026-04-08T10:00:00Z",
    updatedAt: "2026-04-08T10:00:00Z",
    readingTime: 4,
    status: "PUBLISHED",
    tags: "Startup Law, Risk",
    layoutType: "minimal",
    content: JSON.stringify({ type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Speed is not a proxy for stability.' }] }] }),
  },
  {
    id: "grid-3",
    title: "The 110 Crore Deal. The 2-Page AI Contract. The 3-Day Rebuild.",
    slug: "110-crore-ai-contract",
    category: "Contract Law",
    featured: false,
    trending: true,
    author: "The Solitic Core",
    excerpt: "A short reflective with a multi-crore contract worth 110 crores. Made by AI. 2 pages. No dispute subplans. No dispute resolution. No penalty clones. We rebuild it from scratch.",
    createdAt: "2026-04-07T10:00:00Z",
    updatedAt: "2026-04-07T10:00:00Z",
    readingTime: 4,
    status: "PUBLISHED",
    tags: "AI, Legal Tech",
    layoutType: "report",
    content: JSON.stringify({ type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Efficiency should not come at the cost of enforceability.' }] }] }),
  }
];
