[build]
  command = "npx prisma generate && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PRISMA_GENERATE_DATAPROXY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
